### PR TITLE
Delete old examples, use the simple cells created before

### PR DESCRIPTION
**Pull request by raulriera**
Removes all the old examples and just uses the design implemented using the array of simple cells. It looks like this

Screen Shot 2019-04-30 at 3 28 51 PM

### CODE REVIEW

**Comment by runmad** [comment]
Any chance the readme could get cleaned up?

**Comment by raulriera** [comment]
> Any chance the readme could get cleaned up?

What are you looking for?

**Comment by runmad** [comment]
The section on "building custom cells" seems unnecessary now?

**Comment by dannbeaus** [comment]
> The section on "building custom cells" seems unnecessary now?

But developers will still have to build their own cells; but they can copy them out of the demo project now. They are not included in `import FunctionalTableData`

**Comment by raulriera** [comment]
Yeah, I have something prepped.. but I am waiting to finish an article so I can link those too 😏 

Screen Shot 2019-05-01 at 3 51 21 PM

Something like this, with a callback at the bottom to submit new articles with PRs

**Comment by dannbeaus** [comment]
😍 it 🚀

**Pull request merged**
