### PR TITLE
Add support for accessoryViews

### PR DESCRIPTION
**Pull request by jodyscho**
Updating the CellStyle to accept custom accessory views.

### CODE REVIEW

**Comment by krbarnes** [comment]
I wonder if there’s a better way to do this. We added background view when iPhone X was released but I’ve been slowly removing uses of it with intention of deprecating. It’s really expensive to create and destroy views on every render pass.

**Comment by jodyscho** [comment]
I'm open to different implementations but the ability to set the accessoryView simplifies client code. i.e. No need to create custom views to mimic an accessory.

As for being expensive, don't we have the same issue anyways. If a cell needs a custom view then one has to be created regardless.

Let me know what you guys decide.

**Comment by jodyscho** [comment]
Oh, I see. You mean because we create all the HostCells in the render pass we'd potentially be creating a lot of views at that time.

**Comment by jodyscho** [comment]
Maybe something like CombinedView that handles the accessory view. I'll give it some more thought.

**Comment by raulriera** [comment]
I think these should be recreated using CombinedCells, this would be one more API in CellStyle that CollectionView wouldn’t be able to support.

**Pull request closed without merging**
